//-> random gera numero aleatorios entre 0 a 1 
//-> math.floor: remove casas decimais, para ter numeros interios

// let numerosecreto = Math.floor(Math.random()*100)+1
// let tentativa;

// while(tentativa !== numerosecreto){
//     tentativa = Number ( prompt ("Digite um numero de 1 a 100"));

//       if(tentativa>numerosecreto){
//         console.log("O número é menor!");

//     } else if (tentativa < numerosecreto){
//          console.log("O número é maior!");

//     } else {
//         console.log("parabéns! vc acertou!!");
//     }
// }   


// intermediario 3 
// let numero = Number(prompt("Digite um numero"));
// while(numero >=0){
//     console.log(numero);
//     numero--;// numero=numero - 1
// }


// intermediario
// let senha="Betinha";
// let senhadigitado="";

// while(senhadigitado!==senha){
//     senhadigitado=prompt("Digite a senha:");

//     if (senhadigitado!== senha){
//         alert("Senha incorreta! tenta novamente!");
//     }
// }

// alert(" Senha coreta! Acesso permitido!")


//intermediário
// let soma = 0 
// let valor = Number(prompt("Digite um número ou 0 para parar:"));

// while( valor !== 0){
//     soma+= valor;// soma=soma + valor
//     valor=Number(prompt("Digite um numero ou 0 para parar:"));
// }
// console.log("Total da soma:"+ soma);


//intermediário 6
// let somadosvalores =0;
// for(let i=1;i<=3;i++){
//     let valor=Number(prompt(`Digite o Número`));
//     somadosvalores+=valor;// somavalores = somavalores + valor 
// }
// let media = somadosvalores/3
//     console.log("A média é:"+media)


